### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by ursinn** [routeviews/public-issues#127]
### Full Name

Ursin Filli

### ASN

202427

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

2001:7f8:f2:e1:0:20:2427:1

### Multihop

- [ ] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thanks for contributing to the RouteViews project! We've configured the following EBGP session on our AMSIX/LOCIX RouteViews collector:

- asn:  6447
- ipv6: 2001:7f8:f2:e1::6447:1
- fqdn: route-views.amsix.routeviews.org

Relevant `show bgp summary` output:
```
Neighbor                     V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
2001:7f8:f2:e1:0:20:2427:1   4     202427         0         1        0    0    0    never       Active        0 Ursin Filli
```
Please filter out default route and RFC6490 address space.

NOTE: we do not accept addpath-RX or TX on connections.

Many thanks! :-)
