### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by willodc** [routeviews/public-issues#128]
### Full Name

Tiggee LLC

### ASN

16552

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

We peer today, but are missing peers in Frankfurt, New York, Atlanta and Chile.
These are the missing peers:

	ASN	AS Name	IX Name	IPv6	IPv4	On RS	Speed
	6447	RouteViews	DE-CIX Frankfurt	2001:7f8::192f:0:1	80.81.193.49		1 Gbps
	6447	RouteViews	PIT Santiago - PIT Chile	2801:14:9000::6447:1	45.68.17.253		10 Gbps
	6447	RouteViews	DE-CIX New York	2001:504:36::192f:0:1	206.82.105.7		10 Gbps
	6447	RouteViews	Digital Realty Atlanta	2001:478:132::3	198.32.132.3		10 Gbps

### Multihop

- [ ] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thanks for contributing to the RouteViews project! 

Noted that we peer in many locations already. Of the 4 missing, 3 are resource constrained at the moment.

We've configured the following EBGP sessions on the PIT.SCL RouteViews collector:  
  
- asn:  6447  
- ipv4: 45.68.17.253  
- ipv6: 2801:14:9000::6447:1  
- fqdn: pit.scl.routeviews.org  
  
Relevant `show bgp summary` output:  
```  
pit.scl# sh bgp sum | include 16552
Neighbor                V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc  
45.68.16.109            4      16552         0         0        0    0    0    never      Connect        0 Tiggee LLC
2801:14:9000::1:6552:1  4      16552         0         0        0    0    0    never      Connect        0 Tiggee LLC
```  
Please filter out default route and RFC6490 address space.  
  
NOTE: we do not accept addpath-RX or TX on connections.

Many thanks!  :-)
