### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by ember-ana** [routeviews/public-issues#131]
### Full Name

Nettwork

### ASN

200242

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [ ] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thanks for contributing to the RouteViews project! We've configured the following EBGP sessions on the AMSIX/LOCIX RouteViews collector:  
  
- asn:  6447  
- ipv4: 185.1.167.72  
- ipv6: 2001:7f8:f2:e1::6447:1  
- fqdn: route-views.amsix.routeviews.org  
  
Relevant `show bgp summary` output:  
```  
route-views.bknix.routeviews.org# sh bgp sum | include 59238  
Neighbor                     V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc  
185.1.167.149                4     200242         0         1        0    0    0    never       Active        0 Hazel Reimer
2001:7f8:f2:e1:0:20:242:1    4     200242         0         1        0    0    0    never       Active        0 Hazel Reimer
```  
Please filter out default route and RFC6490 address space.  
  
NOTE: we do not accept addpath-RX or TX on connections.

Many thanks! :-)
