### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by ConnorMcF** [routeviews/public-issues#132]
### Full Name

Inferno Communications

### ASN

207841

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [ ] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thanks for contributing to the RouteViews project! We've configured the following EBGP sessions on the LINX RouteViews collector:  
  
- asn: 6447  
- ip4: 195.66.225.222  
- ip6: 2001:7f8:4::192f:1  
- fqdn: route-views.linx.routeviews.org  
  
Relevant 'show bgp summary' output:  
 ```
route-views.linx.routeviews.org# sh bgp sum | include 207841
Neighbor                V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
195.66.227.233          4     207841       749     56154        0    0    0    never       Active        0 Inferno Comms
2001:7f8:4::3:2be1:1    4     207841         0         4        0    0    0    never       Active        0 Inferno Comms 
```
Please filter out default route and RFC6490 address space.  
  
NOTE: we do not accept addpath-RX or TX on connections.

Many thanks! :-)

**Comment by pfsinoz** [comment]
Completed.
