### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by zetserverscom** [routeviews/public-issues#134]
### Full Name

INTERKVM HOST SRL

### ASN

6204

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [ ] Multihop Peering Request

**Comment by pfsinoz** [comment]
As per separate email request, this has been completed at our `amsix.ams.routeviews.org` collector.

Here is the BGP status a few minutes ago:
```
Neighbor                    V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
80.249.214.200              4       6204    312342      1290  2015180    0    0 10:25:03       944676        0 ZET Network
2001:7f8:1::a502:5198:1     4       6204    316792      1298   712368    0    0 10:23:23       194065        0 ZET Network
```
Many thanks! :-)
