### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by louiealad** [routeviews/public-issues#140]
### Full Name

archelle louie datahan

### ASN

150000

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [X] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thank you for your peering request with RouteViews at PhOpenIX.

I've set up the peering session now, and we see that the BGP sessions have established:
```
Neighbor          V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
198.32.172.170    4     150000         6         6     6221    0    0 00:03:42            0        0 Data-Beam Business
2001:478:172::170 4     150000         6         6      202    0    0 00:03:42            0        0 Data-Beam Business
```
When you are ready, we look forward to receiving prefixes from you. RouteViews, being a collector, will not be sending anything.

Many thanks for supporting the RouteViews project!

**Comment by pfsinoz** [comment]
Looking great today, many thanks for peering with RouteViews!
```
Neighbor          V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
198.32.172.170    4     150000    951673      1228  2893184    0    0 20:25:06       949173        0 Data-Beam Business
2001:478:172::170 4     150000    108373      1228   285600    0    0 20:25:06       206699        0 Data-Beam Business
```

**Comment by louiealad** [comment]
thanks much sir!

Regards..
Mr. Archelle Louie Datahan
Data-Byte Computer Sales  & ServicesAeroCam Media-Low altitude Aerial Services
Aparente Street, Cor Salvani Street, Brgy City Hights,General Santos CityTel # 083-552-0933 or 09335543008


like us on Facebook!
http://facebook.com/databytegensanhttp://facebook.com/aerocammedia

 

    On Tuesday, May 14, 2024 at 03:18:49 PM GMT+8, Philip Smith ***@***.***> wrote:  
 
 


Looking great today, many thanks for peering with RouteViews!
Neighbor          V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
198.32.172.170    4     150000    951673      1228  2893184    0    0 20:25:06       949173        0 Data-Beam Business
2001:478:172::170 4     150000    108373      1228   285600    0    0 20:25:06       206699        0 Data-Beam Business
