### ISSUE TITLE
Peering Request AS57344

### ISSUE THREAD

**Issue by sstankovas57344** [routeviews/public-issues#141]
### Full Name

Stefan Stankov

### ASN

57344

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

Multihop peer from Local: 178.132.82.71 and Local: 178.132.82.72

### Multihop

- [X] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thank you for your interesting peering with RouteViews. I've noted from your PeeringDB entry that AS57344 is present at AMS-IX where RouteViews has a collector. Would you be interested in peering with RouteViews at AMS-IX instead of by multi-hop?

**Comment by sstankovas57344** [comment]
Hi,

Unfortunately no. The reason behind this is that our IX peerings are on edge routers over dedicated VRFs for easier distribution around the backbone. In order to collect all our table a multihop bgp is mandatory.

Thank you,
Stefan

**Comment by pfsinoz** [comment]
Ahhh got it, thanks Stefan! Do you have an IPv6 endpoint as well, for IPv6 routes?

**Comment by sstankovas57344** [comment]
Hi
I can provide the IPv6 endpoint in 7 days.

**Comment by pfsinoz** [comment]
Ok, thanks for that! I've set up the multi-hop IPv4 peerings now. Our new collector details are:
```
IPv4: 128.223.51.113
IPv6: 2001:468:d01:33::113
ASN:  6447
FQDN: route-views7.routeviews.org
```
and the BGP sessions are sitting waiting your end now:
```
Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
178.132.82.71   4      57344         0         0        0    0    0    never      Connect        0 Telehouse AD
178.132.82.72   4      57344         0         0        0    0    0    never      Connect        0 Telehouse AD
```
Please let us know if you have any issues with setting up the multihop peering. Many thanks for supporting RouteViews!

**Comment by sstankovas57344** [comment]
Hi,

Thank you for this configuration. May you please help me with a reverse mtr from 128.223.51.113 to 178.132.82.71/72 as there are some firewalls that I need the BGP to pass through. Thank you.

**Comment by pfsinoz** [comment]
Sure, here you go:
<img width="838" alt="Screenshot 2024-05-21 at 16 01 21" src="https://github.com/routeviews/issues/assets/74937641/a6c0aaea-9062-4c0e-bfed-6f14a153e7aa">

**Comment by sstankovas57344** [comment]
Yes I just figured that out. I did a telnet to the server and did it by myself :) The IPv4 BGP are now up. We will prepare the IPv6 in a few days and will let you know the source address. Thank you.

**Comment by pfsinoz** [comment]
Looking good, many thanks!
```
Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
178.132.82.71   4      57344    145540        16  2866867    0    0 00:06:48       952581        0 Telehouse AD
178.132.82.72   4      57344    144955        10  2866867    0    0 00:03:48       952521        0 Telehouse AD
```
Looking forward to IPv6 when you are ready. :-)

**Comment by sstankovas57344** [comment]
Hi

Are you also interested in our companies donating resources for a routeviews platform in Sofia? Please drop me a private email should you express any interest in the same.

**Comment by pfsinoz** [comment]
We are always interested in new sites for RouteViews collectors, thanks for the kind offer! I'll drop you a note, presumable to your contact as per PeeringDB? :-) (I don't think I get to see email addresses via GitHub).

**Comment by sstankovas57344** [comment]
Yes that's cool. thank you.
