### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by CasseTrop** [routeviews/public-issues#142]
### Full Name

O'Neil Castro - Targo Communications Inc.

### ASN

40864

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [x] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [X] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thanks for your request to peer with RouteViews and your interest in the RouteViews project. To be able to set up the EBGP Multihop peerings we would require the IPv4 and IPv6 addresses of your router. Our details are:
```
IPv4: 128.223.51.113
IPv6: 2001:468:d01:33::113
ASN: 6447
FQDN: route-views7.routeviews.org
```
Looking forward to hear from you soon.

**Comment by CasseTrop** [comment]
Hello, here it is:

IPv4: 23.159.240.61
IPv6: 2001:438:fffe::389e/126
ASN: 40864

**Comment by pfsinoz** [comment]
Thanks! I've set up the multihop configuration now, ready whenever you are:
```
Neighbor             V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
23.159.240.61        4      40864         0         1        0    0    0    never       Active        0 Targo
2001:438:fffe::389e  4      40864         0         1        0    0    0    never       Active        0 Targo
```

**Comment by CasseTrop** [comment]
Hello, I can't figure out why it's stuck on Open. Do you see any errors on your side?

My logs only show me this:

 2024 May 30 01:39:12.451 : EC-1250RL : CMLSH : CLI_HIST : User gotar@/dev/pts/1 : CLI : clear ip bgp 128.223.51.113
2024 May 30 01:39:12.452 : EC-1250RL : BGP : INFO : %BGP-3-NOTIFICATION: sending to 128.223.51.113 6/4 (Cease/Administratively Reset.) 0 data-bytes
2024 May 30 01:39:12.452 : EC-1250RL : BGP : NOTIF : [BGP_OPR_NEIGH_STATE_CHANGE_4]: Neighbour [128.223.51.113] Status change opensent -> idle
2024 May 30 01:39:12.452 : EC-1250RL : BGP : INFO : %BGP-3-NOTIFICATION: sending to 128.223.51.113 6/3 (Cease/Peer Unconfigured.) 0 data-bytes
2024 May 30 01:39:12.452 : EC-1250RL : BGP : INFO : %BGP-5-ADJCHANGE: neighbor 128.223.51.113 Down Peer being deleted

**Comment by pfsinoz** [comment]
This is what the collector is reporting:
```
May 30 07:29:04 route-views7 bgpd[6853]: %NOTIFICATION: sent to neighbor 23.159.240.61 6/7 (Cease/Connection Collision Resolution) 0 bytes
May 30 07:29:04 route-views7 bgpd[6853]: [EC 33554452] bgp_process_packet: BGP OPEN receipt failed for peer: 23.159.240.61
May 30 07:29:10 route-views7 bgpd[6853]:  %NOTIFICATION: sent to neighbor 23.159.240.61 4/0 (Hold Timer Expired) 0 bytes
May 30 07:29:12 route-views7 bgpd[6853]: [EC 33554504] 23.159.240.61 unrecognized capability code: 128 - ignored
May 30 07:32:09 route-views7 bgpd[6853]: %NOTIFICATION: sent to neighbor 23.159.240.61 6/7 (Cease/Connection Collision Resolution) 0 bytes
May 30 07:32:09 route-views7 bgpd[6853]: [EC 33554452] bgp_process_packet: BGP OPEN receipt failed for peer: 23.159.240.61
May 30 07:32:12 route-views7 bgpd[6853]: %NOTIFICATION: sent to neighbor 23.159.240.61 4/0 (Hold Timer Expired) 0 bytes
May 30 07:32:13 route-views7 bgpd[6853]: [EC 33554504] 23.159.240.61 unrecognized capability code: 128 - ignored
```
Hmmmm. First one - both sides opened a TCP connection, so one has to drop, seems normal. But then 3 seconds later we get hold timer expired. It could be an MTU issue, and I've tried reducing the MSS, to no avail. It seems like we open the session but don't get anything after that, and hold time expires, repeating the cycle all over again.

**Comment by pfsinoz** [comment]
And for IPv6:
```
May 30 07:34:03 route-views7 bgpd[6853]: [EC 33554455] 2001:438:fffe::389e [Error] bgp_read_packet error: Connection reset by peer
```
which usually means the BGP session has not been configured on the remote.

**Comment by CasseTrop** [comment]
> And for IPv6:
> 
> ```
> May 30 07:34:03 route-views7 bgpd[6853]: [EC 33554455] 2001:438:fffe::389e [Error] bgp_read_packet error: Connection reset by peer
> ```
> 
> which usually means the BGP session has not been configured on the remote.

IPv6 will be configured at a later date.

**Comment by CasseTrop** [comment]
> This is what the collector is reporting:
> 
> ```
> May 30 07:29:04 route-views7 bgpd[6853]: %NOTIFICATION: sent to neighbor 23.159.240.61 6/7 (Cease/Connection Collision Resolution) 0 bytes
> May 30 07:29:04 route-views7 bgpd[6853]: [EC 33554452] bgp_process_packet: BGP OPEN receipt failed for peer: 23.159.240.61
> May 30 07:29:10 route-views7 bgpd[6853]:  %NOTIFICATION: sent to neighbor 23.159.240.61 4/0 (Hold Timer Expired) 0 bytes
> May 30 07:29:12 route-views7 bgpd[6853]: [EC 33554504] 23.159.240.61 unrecognized capability code: 128 - ignored
> May 30 07:32:09 route-views7 bgpd[6853]: %NOTIFICATION: sent to neighbor 23.159.240.61 6/7 (Cease/Connection Collision Resolution) 0 bytes
> May 30 07:32:09 route-views7 bgpd[6853]: [EC 33554452] bgp_process_packet: BGP OPEN receipt failed for peer: 23.159.240.61
> May 30 07:32:12 route-views7 bgpd[6853]: %NOTIFICATION: sent to neighbor 23.159.240.61 4/0 (Hold Timer Expired) 0 bytes
> May 30 07:32:13 route-views7 bgpd[6853]: [EC 33554504] 23.159.240.61 unrecognized capability code: 128 - ignored
> ```
> 
> Hmmmm. First one - both sides opened a TCP connection, so one has to drop, seems normal. But then 3 seconds later we get hold timer expired. It could be an MTU issue, and I've tried reducing the MSS, to no avail. It seems like we open the session but don't get anything after that, and hold time expires, repeating the cycle all over again.

Been trying a few things but keep getting the same results.
Do you have any ideas?

**Comment by pfsinoz** [comment]
I've been trying a few things too. Thought it might be MTU, but not. Finally got success with turning off BGP capability negotiation on the collector:
```
route-views7.routeviews.org# sh bgp sum  | include 40864
23.159.240.61         4      40864    142595       504 22502604    0    0 00:08:42        NoNeg        0 Targo
2001:438:fffe::389e   4      40864         0       179        0    0    0    never       Active        0 Targo
```
I've applied the same configuration for the upcoming IPv6 peering for when you are ready with that.

**Comment by CasseTrop** [comment]
Ok great news, I did turned up IPv6 and it works too but not sending any prefix for now.
Thank you for your help.

**Comment by pfsinoz** [comment]
Oh yes, I see IPv6 up too:
```
23.159.240.61         4      40864    145143       520 22550224    0    0 00:24:48        NoNeg        0 Targo
2001:438:fffe::389e   4      40864    242170       193  7580379    0    0 00:03:09       192072        0 Targo
```
and sending routes too. Full table from both peerings, we really appreciate that!

Thank you for supporting the RouteViews project.

Philip
