### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by macarnellc** [routeviews/public-issues#143]
### Full Name

Macarne LLC

### ASN

64289

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [ ] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thanks for your interest in peering with the RouteViews project. There are several IXes where we are both present although for some of them the collectors are out of capacity. We could peer at:
```
Exchange                                      RV Collector              Router
--------------------------------------------  ------------------------  -------------------------
AMS-IX                                        80.249.213.84             80.249.208.221
AMS-IX                                        2001:7f8:1::a500:6447:2   2001:7f8:1::a506:4289:1
SFMIX                                         206.197.187.28            206.197.187.51
SFMIX                                         2001:504:30::ba00:6447:1  2001:504:30::ba06:4289:1
DE-CIX New York: DE-CIX New York Peering LAN  206.82.105.7              206.82.104.251
DE-CIX New York: DE-CIX New York Peering LAN  2001:504:36::192f:0:1     2001:504:36::fb21:0:2
DE-CIX New York: DE-CIX New York Peering LAN  206.82.105.7              206.82.104.147
DE-CIX New York: DE-CIX New York Peering LAN  2001:504:36::192f:0:1     2001:504:36::fb21:0:1
```
Please let us know which of the above locations you'd be happy to peer at (or if all the above), and we will get the configurations in place at our end.

Philip

**Comment by macarnellc** [comment]
Hi, all are fine for us. So yes we are happy to setup sessions on all
locations thanks Arne

**Comment by macarnellc** [comment]
Hi, our sessions are configured. Please let me know when your side is
ready. Thanks, Arne

**Comment by pfsinoz** [comment]
Hello Arne...

I've set up the sessions now. This is our Amsterdam collector:
```
80.249.208.221              4      64289    232040        28 61614609    0    0 00:02:36       947143        0 Macarne LLC
2001:7f8:1::a506:4289:1     4      64289     58504        29 37900580    0    0 00:02:40       193580        0 Macarne LLC
```
looking good.

This is on our SFMIX collector:
```
206.197.187.51           4      64289         0         0        0    0    0    never      Connect        0 Macarne LLC
2001:504:30::ba06:4289:1 4      64289         0         0        0    0    0    never      Connect        0 Macarne LLC
```
Doesn't look like we can connect on TCP/179 as yet. I'm using the address listed in PeeringDB, so hopefully I got this correct.

This is on our DE-CIX New York collector:
```
206.82.104.147           4      64289         0         0        0    0    0    never      Connect        0 Macarne LLC
206.82.104.251           4      64289    143245         5 69344466   45    0 00:01:26       888646        0 Macarne LLC
2001:504:36::fb21:0:1    4      64289         0         0        0    0    0    never       Active        0 Macarne LLC
2001:504:36::fb21:0:2    4      64289     55407         5 58701009    0    0 00:01:26       193580        0 Macarne LLC
```
One of the peers is up, the other one is still down. Or did you only want to send a feed from one of the routers?

Philip

**Comment by macarnellc** [comment]
Hi,

SFMIX I will set up the session in the next 48 hours. We are just in the
process of switching the Equipment in Santa Clara. Sorry for that.

And yes in DE-CIX NYC we only set up one of the routers. I hope that's fine?

Btw. do you have any collectors in LA like Any2 or Equinix IX?

Thanks, Arne

**Comment by pfsinoz** [comment]
Hi Arne...  Ok, I'll remove the 2nd DECIX NY peering - one is just fine. For SFMIX, no issues, we are ready whenever you are. For Los Angeles, we are hosted by CENIC at PacWave - that's R&E focus. But we are adding new collectors as hosts/IXes/DCs volunteer to host them, so hopefully we can have a presence at Equinix in LA soon. We keep our PeeringDB entry up to date, and do announce the new collectors on the RouteViews website (and in any regular NOG / Peering Forum presentations).

Philip

**Comment by macarnellc** [comment]
Hi Philip,

Sound great. What kind of resources you need to run a collector? More than happy to help.

Thanks, Arne

**Comment by pfsinoz** [comment]
The ideal is a VM with 4 VCPU, 32G RAM, 200G disk, with one LAN interface on the IX itself, and the other LAN interface for admin access and transit for sending the BGP table dump and BGP update dumps back to archive.routeviews.org at the Uni of Oregon. Most of the collectors are donated/hosted by IXes themselves, but some of them are hosted by IX members (who also donate the cost of the IX port that the collector needs). We sometimes also have hardware collectors (1RU server) in places where it's not possible for the IX (or IX member) to host a VM for us, but we prefer not to do that as these are more difficult to maintain (hardware gets old, etc).

**Comment by macarnellc** [comment]
Will check how we can do this and get back to you in the next few days.
Thanks, Arne

**Comment by pfsinoz** [comment]
Thanks, Arne, much appreciated!

**Comment by pfsinoz** [comment]
Hello Arne... Just wondering how you are getting on with your Santa Clara equipment switch, and if you had a chance to look at setting up the peering with the RouteViews collector at SFMIX  yet. Still showing down at our end:
```
Neighbor                 V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
206.197.187.51           4      64289         0         0        0    0    0    never      Connect        0 Macarne LLC
2001:504:30::ba06:4289:1 4      64289         0         0        0    0    0    never      Connect        0 Macarne LLC
```

**Comment by macarnellc** [comment]
Hi, I was a bit busy - the team is currently at Nanog. But I will take care
of this asap. Sorry for the delay. Greetings, Arne

**Comment by macarnellc** [comment]
Hi, should be up now. Thanks, Arne

**Comment by pfsinoz** [comment]
Hey Arne...

Yes they both are, confirmed:
```
Neighbor                 V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
206.197.187.51           4      64289    717613      1816 66384017    0    0 1d06h13m       940332        0 Macarne LLC
2001:504:30::ba06:4289:1 4      64289      2124      1813 37684786    0    0 1d06h10m            0        0 Macarne LLC
```
although we are not receiving any prefixes on the IPv6 peering.

**Comment by macarnellc** [comment]
Hi. Let me check thanks Arne

**Comment by pfsinoz** [comment]
Hey Arne...

Yes they both are, confirmed:
```
Neighbor                 V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
206.197.187.51           4      64289  22372645     36590 54244348    0    0 02w2d00h       943176        0 Macarne LLC
2001:504:30::ba06:4289:1 4      64289  11639566     36590 33656756    0    0 02w2d00h       204406        0 Macarne LLC
```
Looking good!

**Comment by macarnellc** [comment]
Hi, hope you are doing fine? Can we setup a sessions at AMSIX please?
Thanks, Arne
