### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by peer-1** [routeviews/public-issues#146]
### Full Name

Fabio Escorpioni

### ASN

999

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

IX.BR Sao Paulo

187.16.210.69
2001:12f8::210:69

### Multihop

- [ ] Multihop Peering Request

**Comment by pfsinoz** [comment]
Hi Fabio,

Thanks very  much for your peering request at IX.br Sao Paulo... Unfortunately our Sao Paulo collector is full.However, I see you are at IX.br in Rio. Would you be interested in peering with RouteViews there instead? Our details are in our PeeringDB entry: https://www.peeringdb.com/asn/6447. Please let us know, and I'd be happy to set this up.

Thanks!

**Comment by pfsinoz** [comment]
Now completed, thanks for supporting the RouteViews project!
