### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by moegugu** [routeviews/public-issues#150]
### Full Name

MoeDove LLC

### ASN

44324

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [ ] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thanks for getting in touch with RouteViews. The only locations we have overlap is at LOCIX in Frankfurt, and the collector serving LOCIX is at capacity right now. We are re-arranging some of the infrastructure there, and once that is ready we will be able to set up the peering.

Many thanks!

**Comment by pfsinoz** [comment]
We've got some extra capacity at our LOC-IX collector now... Are you still interested in setting up the peering with RouteViews? If so, please let us know, and I'll set up the BGP sessions.

**Comment by moegugu** [comment]
Yes, please set up BGP session

**Comment by pfsinoz** [comment]
I've now set up the BGP sessions:
```
Neighbor                     V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
185.1.167.50                 4      44324         0         0        0    0    0    never       Active        0 MoeDove Global
2001:7f8:f2:e1:0:4:4234:2    4      44324    136905         9 19033980    0    0 00:06:26       206887        0 MoeDove Global
```
The IPv6 session came up straight away, but the IPv4 session is sitting waiting.

Best wishes!
