### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by akshaykodali** [routeviews/public-issues#152]
### Full Name

FastPix

### ASN

401021

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

23.176.152.1
2620:0:8001:a1b1::a

### Multihop

- [X] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thanks for getting in touch with RouteViews and requesting a peering. We will set up the multihop BGP sessions on our route-views7.routeviews.org collector. It's details are:
```
IPv4: 128.223.51.113
IPv6: 2001:468:d01:33::113
ASN:  6447
```
Please let us know when the configuration is ready at your end and we will set up our end.

Many thanks for your interest in and supporting the RouteViews project.

**Comment by akshaykodali** [comment]
Hi Phillip,

The configuration is active on our end. Our IPv4 peer address is 23.176.152.1 (I've mistakenly mentioned 23.176.152.0 earlier) and IPv6 address is 2620:0:8001:a1b1::a (no change).

**Comment by pfsinoz** [comment]
Thanks Akshay!!

I've configured the peerings now, and they are both up:
```
Neighbor               V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
23.176.152.1           4     401021    147633         4 56107712    0    0 00:01:01       942020        0 FastPix
2620:0:8001:a1b1::a    4     401021     46815         4  9691145    0    0 00:01:01       191428        0 FastPix
```
Many thanks for supporting RouteViews. :-)

**Comment by akshaykodali** [comment]
Thank you Phillip!
