### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by raymonvdm** [routeviews/public-issues#155]
### Full Name

Solcon Internetdiensten B.V,

### ASN

12414

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

The following sessions are down since 17h

80.249.208.165
80.249.209.165

2001:7f8:1::a501:2414:1
2001:7f8:1::a501:2414:2

### Multihop

- [ ] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thanks for getting in touch! Yes, our host is carrying out urgent maintenance of their infrastructure which included taking the route-views.amsix.routeviews.org collector offline. We don't have an ETA for completion as yet.

If you are interested, we'd like to move you to our new collector at AMS-IX as the original collector you peer with is heavily loaded. Our new collector's details are:
```
IPv4: 80.249.213.84
IPv6: 2001:7f8:1::a500:6447:2
ASN:  6447
FQDN: amsix.ams.routeviews.org
```

Please let us know if you'd like to go ahead with the move, and we'll set up the BGP configuration at our end.

Thanks!
