### ISSUE TITLE
403 Forbidden on Collector Subpages

### ISSUE THREAD

**Issue by sattler** [routeviews/public-issues#160]
### Effected Services/Hosts

archive.routeviews.org

### Details

Several (any?) links on the archive subpage result in a 403 Forbidden response by the server. E.g., https://archive.routeviews.org/route-views4/bgpdata

I tested this from four different networks and found it to be not specific to the network I am using (no address space based blocking).

This also affects all previously existing subpages (e.g., https://archive.routeviews.org/route-views4/bgpdata/2024.07/RIBS/rib.20240731.0000.bz2)

**Comment by ppaeps** [comment]
Thanks for your report.

Storage got stuck. I've managed to unstick it. Archived data should be available again.

A couple of archives from today will be missing until we put them where they belong. I'll update here when that's done.

**Comment by ppaeps** [comment]
This should be fixed. Can you please confirm? Thanks!

**Comment by sattler** [comment]
According to my minimal tests it's working again. Thank you for your work!

**Comment by ppaeps** [comment]
Thank you for confirming! 🙏
