### ISSUE TITLE
Unable to access RouteView FTP archive files

### ISSUE THREAD

**Issue by netzgit** [routeviews/public-issues#161]
### Effected Services/Hosts

archive.routeviews.org

### Details

I’m trying to access the RouteView archive via ftp://archive.routeviews.org/, but it seems to be empty. I also can’t access the links at the archive website, for example https://archive.routeviews.org/route-views3/bgpdata (Forbidden), already mentioned in #160

**Comment by ppaeps** [comment]
Thanks for your report.

Storage got stuck.  I've managed to unstick it.  Archived data should be available again.

A couple of archives from today will be missing until we put them where they belong.  I'll update here when that's done.

**Comment by ppaeps** [comment]
This should be fixed.  Can you please confirm?  Thanks!

**Comment by netzgit** [comment]
Hi, thanks for the fix! I can confirm it's working again.
