### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by erickhuge** [routeviews/public-issues#162]
### Full Name

Huge Networks

### ASN

264409

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

Hi,

Let's peer.

Please let's peer over eBGP/Multihop through 167.114.47.228 <> route-views2.routeviews.org -  max TTL 255 

We will send our Full BGP feeds. 

### Multihop

- [X] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thanks for your request! We already peer at FLIX, Fortaleza, Sao Paulo and at Rio. What advantage would there be adding a multihop peering? We reserve the latter for those who are not present at Internet Exchange Points (our preferred peering location), or who are giving substantially different views of the routing table (for example only peering routes at IXes, and the full table for multihop). If you would clarify please. :-) Thanks!

**Comment by erickhuge** [comment]
Hi Philip,

Of course. Basically we don't have IGP/BGP between some of our POPs in North America and Europe, which have many more routes available.

Because of that, we're migrating many of our routers to this RR.

**Comment by pfsinoz** [comment]
Ah understood! Ok, let's set up the multi-hop. It will be to route-views7.routeviews.org though, as route-views2 is at capacity. Details are:
```
IPv4: 128.223.51.113
IPv6: 2001:468:d01:33::113
ASN:  6447
```
Please let me know when your end is ready, and I'll set up the RouteViews 7 collector.

Thanks!

**Comment by pfsinoz** [comment]
Did you want to go ahead with this? If so, please reopen the case, thanks!

**Comment by erickhuge** [comment]
Hi Philip,

Sure, let's go ahead, please use 64.176.198.142 on our end.
