### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by as56987** [routeviews/public-issues#163]
### Full Name

ABACLOUDA

### ASN

56987

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

Hello,
We would like to add AMS-IX session in addition to our existing multi-hop session.

### Multihop

- [ ] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thanks for getting in touch with RouteViews! I've set up the BGP sessions at AMS-IX now as per your PeeringDB entry:
```
Neighbor                    V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
80.249.211.234              4      56987         0         0        0    0    0    never       Active        0 Abaclouda
2001:7f8:1::a505:6987:1     4      56987         0         0        0    0    0    never       Active        0 Abaclouda
```
Our collector details are:
```
IPv4: 80.249.213.84
IPv6: 2001:7f8:1::a500:6447:2
ASN: 6447
FQDN: amsix.ams.routeviews.org
```
Please let us know if you have any issues with bringing up the BGP sessions.

Best wishes!

**Comment by as56987** [comment]
Sessions are UP, thank you
