### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by louiealad** [routeviews/public-issues#164]
### Full Name

archelle louie datahan

### ASN

150000

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

peering Bgp ip v4 is 203.82.39.122
peering Bgp ip v6 is 2401:8e80::21

for Ph Open IX Billateral Session

peering Bgp ip v4 is 198.32.172.171
peering Bgp ip v6 is 2001:478:172::171

### Multihop

- [X] Multihop Peering Request

**Comment by pfsinoz** [comment]
I've added the 2nd bilateral peering at PhOpenIX now. Just to note that the original bilateral we set up in May has been down for the last 4 days. And also your PeeringDB entry says you have two peering addresses at PhOpenIX. Is the original peering going away, or are you planning to bring it back up?

This is the status now:
```
Neighbor          V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
198.32.172.170    4     150000     63236     23712        0    0    0 4d07h01m       Active        0 Data-Beam Business
198.32.172.171    4     150000         0         3        0    0    0    never       Active        0 Data-Beam Business
2001:478:172::170 4     150000     24351     23713        0    0    0 4d07h01m       Active        0 Data-Beam Business
2001:478:172::171 4     150000         0         3        0    0    0    never       Active        0 Data-Beam Business
```
Please let us know!

Also, is there any reason you are asking for multi-hop peering as well? We generally set those up for peers who are not present at Internet Exchange Points. Do let us know, please.

**Comment by louiealad** [comment]
Hello thanks for setting up our 2nd peering. our first peering still up. just encountered foc break on field and still functioning.thnx!

**Comment by louiealad** [comment]
both ipv4 and v6 on our 2nd peering now up.thanks!

**Comment by pfsinoz** [comment]
Ok, understood, thanks for letting us know. Status now:
```
Neighbor          V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
198.32.172.170    4     150000     63236     23712        0    0    0 4d07h14m       Active        0 Data-Beam Business
198.32.172.171    4     150000    289470        16 32203929    0    0 00:04:53       968579        0 Data-Beam Business
2001:478:172::170 4     150000     24351     23713        0    0    0 4d07h14m       Active        0 Data-Beam Business
2001:478:172::171 4     150000     68993        25 18150245    0    0 00:04:58       207738        0 Data-Beam Business
```
Thanks very much!

**Comment by louiealad** [comment]
thanks!
Regards..
Mr. Archelle Louie Datahan
Data-Byte Computer Sales  & ServicesAeroCam Media-Low altitude Aerial Services
Aparente Street, Cor Salvani Street, Brgy City Hights,General Santos CityTel # 083-552-0933 or 09335543008


like us on Facebook!
http://facebook.com/databytegensanhttp://facebook.com/aerocammedia

 

    On Saturday, September 7, 2024 at 05:02:15 PM GMT+8, Philip Smith ***@***.***> wrote:  
 
 


I've added the 2nd bilateral peering at PhOpenIX now. Just to note that the original bilateral we set up in May has been down for the last 4 days. And also your PeeringDB entry says you have two peering addresses at PhOpenIX. Is the original peering going away, or are you planning to bring it back up?

This is the status now:
Neighbor          V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
198.32.172.170    4     150000     63236     23712        0    0    0 4d07h01m       Active        0 Data-Beam Business
198.32.172.171    4     150000         0         3        0    0    0    never       Active        0 Data-Beam Business
2001:478:172::170 4     150000     24351     23713        0    0    0 4d07h01m       Active        0 Data-Beam Business
2001:478:172::171 4     150000         0         3        0    0    0    never       Active        0 Data-Beam Business

Please let us know!

Also, is there any reason you are asking for multi-hop peering as well? We generally set those up for peers who are not present at Internet Exchange Points. Do let us know, please.
