### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by deltadragon** [routeviews/public-issues#165]
### Full Name

Delta Cloud

### ASN

8860

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [ ] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thanks for your interest in RouteViews! We are not present at any of the IXPs you list in your PeeringDB entry (our DE-CIX Frankfurt collector has been out of service awaiting replacement for quite some time). Would you be interested in an EBGP Multihop peering instead? This would be to one of our collectors at the University of Oregon.
