### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by herzadigital** [routeviews/public-issues#168]
### Full Name

Hernan Gibran Ramadhan

### ASN

AS140443

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [ ] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thanks for your interest in peering with RouteViews!

We overlap here:
```
- RouteViews (ASN: 6447), and
- Herza Cloud (ASN: 140443).

Exchange           RV Collector             Router
-----------------  -----------------------  --------------------------
Equinix Singapore  27.111.228.208           27.111.230.188
Equinix Singapore  2001:de8:4::6447:1       2001:de8:4::14:443:1
AMS-IX             80.249.213.84            80.249.214.177
AMS-IX             2001:7f8:1::a500:6447:2  2001:7f8:1:0:a500:14:443:1
DE-CIX ASEAN       103.162.254.36           103.162.254.113
DE-CIX ASEAN       2001:df6:480::192f:0:1   2001:df6:480:0:2:249b:0:1
```
so we'd be happy to peer with you at these three locations if you are willing?

Please let us known what works for you and we can get the configuration in place.

**Comment by herzadigital** [comment]
Hi Philip,

It was so great to meet you in SGNOG yesterday and discussing about the next Apricot. Finger cross for Penang 😃

I have set BGP in our side for all three session. Waiting for you to turn up the bgp session.

Thank you very much.


Sincerely,
Hernan Gibran Ramadhan
======================
[A black and blue logo  Description automatically generated]
HERZA CLOUD & DATACENTER
Web Hosting, Virtualization and Colocation

PT. Herza Digital Indonesia
***@***.***, Tower A – 12th Floor
Jl. Kasablanka Raya Kav. 88, South Jakarta 12870 - Indonesia

Phone: (021) 50515111 / Fax: (021) 5010 6321
WhatsApp: +62-811-861555<https://wa.me/62811861555> (Sales)  / +62-811-205599<https://wa.me/62811205599> (Billing)

Website: www.herza.id<https://www.herza.id/> | Email: ***@***.******@***.***>
SINGAPORE CORPORATION:
Herza Singapore Pte Ltd
68 Circular Road #02-01, Singapore 049422

Phone: +65-31064872
Website: www.herza.sg<http://www.herza.sg/> | Email: ***@***.******@***.***>

MAKASSAR BRANCH:
GRAHA PENA TOWER, 5th Floor
Jl. Urip Sumoharjo No. 20,
Makassar, Sulawesi Selatan 90231, INDONESIA
[A black and white label with text  Description automatically generated]       [A black and white label with text and a logo  Description automatically generated]        [A close-up of a logo  Description automatically generated]
***@***.***<https://dunsregistered.dnb.com/DunsRegisteredProfileAnywhere.aspx?Key1=3175222&PaArea=Mail>


This message and any attachments are confidential and intended for the named addressee(s) only. If you have received this message in error, please notify immediately the sender, then delete the message. Any unauthorized modification, edition, use or dissemination is prohibited. The sender shall not be liable for this message if it has been modified, altered, falsified, infected by a virus or even edited or disseminated without authorization.

Pesan ini dan semua lampirannya bersifat rahasia dan ditujukan untuk penerima yang disebutkan saja. Jika Anda menerima pesan ini karena kesalahan, harap segera beri tahu pengirimnya, lalu hapus pesan tersebut. Modifikasi, edisi, penggunaan, atau penyebaran yang tidak sah dilarang. Pengirim tidak bertanggung jawab atas pesan ini jika telah dimodifikasi, diubah, dipalsukan, terinfeksi virus atau bahkan diedit atau disebarluaskan tanpa izin.

**Comment by herzadigital** [comment]
Hi Philip,

I havent receive any respond from you. Our BGP is configured but not yet established.

27.111.228.208         6447          0          0       0       0 2d 12:01:56 Active
80.249.213.84          6447          0          0       0       0 2d 12:01:56 Active
103.162.254.36         6447          0          0       0       0 2d 12:01:56 Active
2001:7f8:1::a500:6447:2        6447          0          0       0       0 2d 12:01:56 Active
2001:de8:4::6447:1        6447          0          0       0       0 2d 12:01:56 Active
2001:df6:480::192f:0:1        6447          0          0       0       0 2d 12:01:56 Active

Looking forward to hear from you soon.


Sincerely,
Hernan Gibran Ramadhan
======================
[A black and blue logo  Description automatically generated]
HERZA CLOUD & DATACENTER
Web Hosting, Virtualization and Colocation

PT. Herza Digital Indonesia
***@***.***, Tower A – 12th Floor
Jl. Kasablanka Raya Kav. 88, South Jakarta 12870 - Indonesia

Phone: (021) 50515111 / Fax: (021) 5010 6321
WhatsApp: +62-811-861555<https://wa.me/62811861555> (Sales)  / +62-811-205599<https://wa.me/62811205599> (Billing)

Website: www.herza.id<https://www.herza.id/> | Email: ***@***.******@***.***>
SINGAPORE CORPORATION:
Herza Singapore Pte Ltd
68 Circular Road #02-01, Singapore 049422

Phone: +65-31064872
Website: www.herza.sg<http://www.herza.sg/> | Email: ***@***.******@***.***>

MAKASSAR BRANCH:
GRAHA PENA TOWER, 5th Floor
Jl. Urip Sumoharjo No. 20,
Makassar, Sulawesi Selatan 90231, INDONESIA
[A black and white label with text  Description automatically generated]       [A black and white label with text and a logo  Description automatically generated]        [A close-up of a logo  Description automatically generated]
***@***.***<https://dunsregistered.dnb.com/DunsRegisteredProfileAnywhere.aspx?Key1=3175222&PaArea=Mail>


This message and any attachments are confidential and intended for the named addressee(s) only. If you have received this message in error, please notify immediately the sender, then delete the message. Any unauthorized modification, edition, use or dissemination is prohibited. The sender shall not be liable for this message if it has been modified, altered, falsified, infected by a virus or even edited or disseminated without authorization.

Pesan ini dan semua lampirannya bersifat rahasia dan ditujukan untuk penerima yang disebutkan saja. Jika Anda menerima pesan ini karena kesalahan, harap segera beri tahu pengirimnya, lalu hapus pesan tersebut. Modifikasi, edisi, penggunaan, atau penyebaran yang tidak sah dilarang. Pengirim tidak bertanggung jawab atas pesan ini jika telah dimodifikasi, diubah, dipalsukan, terinfeksi virus atau bahkan diedit atau disebarluaskan tanpa izin.


From: Hernan Gibran Ramadhan
Sent: 28 September 2024 21:07
To: routeviews/issues ***@***.***>
Subject: RE: [routeviews/issues] Peering Request (Issue #168)

Hi Philip,

It was so great to meet you in SGNOG yesterday and discussing about the next Apricot. Finger cross for Penang 😃

I have set BGP in our side for all three session. Waiting for you to turn up the bgp session.

Thank you very much.


Sincerely,
Hernan Gibran Ramadhan
======================
[A black and blue logo  Description automatically generated]
HERZA CLOUD & DATACENTER
Web Hosting, Virtualization and Colocation

PT. Herza Digital Indonesia
***@***.***, Tower A – 12th Floor
Jl. Kasablanka Raya Kav. 88, South Jakarta 12870 - Indonesia

Phone: (021) 50515111 / Fax: (021) 5010 6321
WhatsApp: +62-811-861555<https://wa.me/62811861555> (Sales)  / +62-811-205599<https://wa.me/62811205599> (Billing)

Website: www.herza.id<https://www.herza.id/> | Email: ***@***.******@***.***>
SINGAPORE CORPORATION:
Herza Singapore Pte Ltd
68 Circular Road #02-01, Singapore 049422

Phone: +65-31064872
Website: www.herza.sg<http://www.herza.sg/> | Email: ***@***.******@***.***>

MAKASSAR BRANCH:
GRAHA PENA TOWER, 5th Floor
Jl. Urip Sumoharjo No. 20,
Makassar, Sulawesi Selatan 90231, INDONESIA
[A black and white label with text  Description automatically generated]       [A black and white label with text and a logo  Description automatically generated]        [A close-up of a logo  Description automatically generated]
***@***.***<https://dunsregistered.dnb.com/DunsRegisteredProfileAnywhere.aspx?Key1=3175222&PaArea=Mail>


This message and any attachments are confidential and intended for the named addressee(s) only. If you have received this message in error, please notify immediately the sender, then delete the message. Any unauthorized modification, edition, use or dissemination is prohibited. The sender shall not be liable for this message if it has been modified, altered, falsified, infected by a virus or even edited or disseminated without authorization.

Pesan ini dan semua lampirannya bersifat rahasia dan ditujukan untuk penerima yang disebutkan saja. Jika Anda menerima pesan ini karena kesalahan, harap segera beri tahu pengirimnya, lalu hapus pesan tersebut. Modifikasi, edisi, penggunaan, atau penyebaran yang tidak sah dilarang. Pengirim tidak bertanggung jawab atas pesan ini jika telah dimodifikasi, diubah, dipalsukan, terinfeksi virus atau bahkan diedit atau disebarluaskan tanpa izin.

**Comment by hanskuhn** [comment]
Hello! Philip is currently traveling so we appreciate your patience.

We should be able to get you a reply in the next day or two. Thanks for supporting RouteViews.

**Comment by nihb333** [comment]
Hi Hernan

I am Nina, one of Phillips colleagues. I have configured our side and see all the sessions up.  Thanks for supporting RouteViews! 

I see that you announce your peering routes to us.  If you want to announce your full table to us , please feel free to do so at the AMS-IX and DE-CIX ASEAN sessions.  

Thanks for peering!

Nina



amsix.ams# sh bg su | include 140443
80.249.214.177  4     140443         8         4 131558141    0    0 00:01:20           61        0 Herza Cloud
2001:7f8:1:0:a500:14:443:1  4     140443         5         4 105632145    0    0 00:01:20            1        0 Herza Cloud

decix.jhb# sh bg su | include 140443
103.162.254.113 4     140443         8         3 48869013    0    0 00:00:58           61        0 Herza Cloud
2001:df6:480:0:2:249b:0:1 4     140443         5         3 19094276    0    0 00:00:58            1        0 Herza Cloud
decix.jhb# 

route-views.sg# sh bg su | include 140443
27.111.230.188  4     140443         9         4 214063057    0    0 00:01:20           58        0 Herza Cloud
2001:de8:4::14:443:1  4     140443         5         4 306029710    0    0 00:01:20            2        0 Herza Cloud
route-views.sg#
