### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by ahadley1124** [routeviews/public-issues#169]
### Full Name

Austin Hadley sole proprietorship

### ASN

17290

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

2602:fa86:00ff::/48

### Multihop

- [X] Multihop Peering Request

**Comment by nihb333** [comment]
Hi Austin
Thank You for your interest in the RouteViews project. Unfortunately we do not see neither your ASN or prefix on the internet  hence you do not meet the requirements for peering with RouteViews.  
Kind Regards
Nina

**Comment by ahadley1124** [comment]
I have secured a IX and my equipment is going in this week. I would you like me to let you know in this issue or a new issue when the equipment is running and everything public?

**Comment by pfsinoz** [comment]
Yes please, Austin. Either re-open this one, or create a new one, up to you. Also, if you are able to share your copy of the full BGP table as you see it, with RouteViews, that will really help!
