### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by as400442** [routeviews/public-issues#171]
### Full Name

AS400442

### ASN

400442

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

23.133.168.1
2602:FBC7:4::1

### Multihop

- [X] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thank you for your interest in RouteViews.

We'd be happy to set up a multi-hop peering with you, using our route-views7 collector. Details:
```
IPv4: 128.223.51.113
IPv6: 2001:468:d01:33::113
ASN:  6447
FQDN: route-views7.routeviews.org
```
Please let us know when you have set up the configuration and we will set up our end.

Thanks!

**Comment by as400442** [comment]
Sorry for the delay; routes configured.

-------- Original Message --------
Subject: Re: [routeviews/issues] Peering Request (Issue #171)
Date: Friday, October 18, 2024 18:21 CDT
From: Philip Smith ***@***.***>
Reply-To: routeviews/issues ***@***.***>

To: routeviews/issues ***@***.***>
CC: as400442 ***@***.***>, Author ***@***.***>

References: 




 
 
Thank you for your interest in RouteViews.
We'd be happy to set up a multi-hop peering with you, using our route-views7 collector. Details:IPv4: 128.223.51.113
IPv6: 2001:468:d01:33::113
ASN:  6447
FQDN: route-views7.routeviews.org

Please let us know when you have set up the configuration and we will set up our end.
Thanks!

**Comment by nihb333** [comment]
Hi 
Our side is done and sessions are up - thanks for the support!

23.133.168.1    4     400442    953202         5 170362762    0    0 00:02:12       954993        0 Vulpine Networks
2602:fbc7:4::1          4     400442     90460         5 98074093    0    0 00:02:12       203401        0 Vulpine Networks
route-views7.routeviews.org#
