### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by brunofrazao-huge** [routeviews/public-issues#173]
### Full Name

 Huge Networks

### ASN

AS264409

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

Here are the requested IP information:

IPv4: 45.6.55.214/32
IPv6: 2001:12f8:0:2::55:214/128

### Multihop

- [X] Multihop Peering Request

**Comment by pfsinoz** [comment]
Thank you for your interest in RouteViews.

The addresses you provided are at IX.br in Rio where we already peer with you on 45.6.55.6/2001:12f8:0:2::55:6 (not multihop as in the request).

Let me know if this is correct and I'll set up the other peerings as well.

Thanks!

**Comment by brunofrazao-huge** [comment]
Yes, that's correct, we have peering with you at IX.br in Rio, but at another location (PIX INTERNEXA).

This other one would be at PIX EQUINIX-RJ2.

Just to clarify, the new connection will also not be multihop, ok.

I'm available for any questions.

Regards,

**Comment by brunofrazao-huge** [comment]
Hello Philip.

Any update on the above request?

Regards,

**Comment by brunofrazao-huge** [comment]
Hello Philip,

I hope you're doing well.

I'm following up on my previous message regarding the peering request. Could you provide any updates or let me know if there are any additional steps needed from my side?

I appreciate your time and look forward to your response.

Best regards,

**Comment by brunofrazao-huge** [comment]
Hello Philip,

Any updates on the request above? I'm still waiting.

Best regards,

**Comment by brunofrazao-huge** [comment]
Hello Philip,

Any updates on the request above?

Best regards,

**Comment by nihb333** [comment]
Hi 
Sorry about the delay.  We'd be happy to set up a second session.  I notice that you are not announcing your full table to us in Rio.  Would that be possible? 
BR Nina

**Comment by brunofrazao-huge** [comment]
Hello,

That's correct, we don't send the full table in these peerings, we only announce a few prefixes. So, in this case, we will follow the same pattern as the other session we already have.

I'll be waiting for the information about the new session.

Best regards,

**Comment by nihb333** [comment]
We do prefer if you can send your full table.  Will the prefixes announced on this second session in Rio be different from the ones on first?  Sorry for all my questions, but if there is no new information from the new session, we prefer to keep just the one due to capacity restraints.

**Comment by brunofrazao-huge** [comment]
Hello,

I checked internally with the team and we're going to send full table in this new session, ok.

I'll be waiting for the information about the new session.

Best regards,

**Comment by nihb333** [comment]
Hi 
Please set up the sessions to the addresses below and let us know when done. Then we will configure our side

Thanks

as: 6447
v4: 45.6.52.213 
v6: 2001:12f8:0:2::213

**Comment by brunofrazao-huge** [comment]
Hello.

Session has been configured with the information provided above. Awaiting configuration on your side.

Regards,

**Comment by nihb333** [comment]
Our side is configured  and up.  We do not see the full table on tis new session, but the old one is now a full table.  Will you announce the full table on both? 

route-views.rio.routeviews.org# sh bg su | include 264409
45.6.55.6       4     264409   5898241    173153 99319125    0    0 01w2d15h       864802        0 Huge Networks -
45.6.55.214     4     264409       187        13 99319125    0    0 00:05:21          456        0 Huge Networks -
2001:12f8:0:2::55:6   4     264409  16913197    173153 89952819    0    0 01w2d15h            1        0 Huge Networks -
2001:12f8:0:2::55:214 4     264409        14        13 89952819    0    0 00:05:21            0        0 Huge Networks -

**Comment by brunofrazao-huge** [comment]
Hello,

We made a change on our side and are now sending the full table in the session, as shown in the output below. Could you please validate and give us your feedback?

45.6.52.213
RouteViews
6447 23087 0 08d00h22m 0/0/974419 (IPv4)
378920 0

Best regards,

**Comment by nihb333** [comment]
I see full routes on the v4 sessions, but still not on one  v6 session - it would be great if you could update that at your convinience, but let's close this ticket here 

Thanks for your patience :)
route-views.rio.routeviews.org# sh bg su | include 264409
45.6.55.6       4     264409   8307534    211478 120951796    0    0 03w1d23h       865734        0 Huge Networks -
45.6.55.214     4     264409   1331153     38338 120951796    0    0 01w6d07h       974774        0 Huge Networks -
2001:12f8:0:2::55:6   4     264409  16952826    211477 128781208    0    0 03w1d23h            1        0 Huge Networks -
2001:12f8:0:2::55:214 4     264409    217575     38338 128781208    0    0 01w6d07h        77996        0 Huge Networks -
route-views.rio.routeviews.org# 

Kind Regards
Nin
