### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by benoitc** [routeviews/public-issues#174]
### Full Name

Enki Multimedia

### ASN

209823

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [ ] Multihop Peering Request

**Comment by nihb333** [comment]
Hi Benoit
Thanks for reaching out.  We will be happy to peer with you.  It looks like our mutal location is DE-CIX New York.  Would you be able to send us your full table at this location?  We prefer to received the full table if possible. Please let us know if this is agreeable to you and go ahead at configure your side,

Kind Regards
Nina


Potential BGP Peerings for networks:

- RouteViews (ASN: 6447), and 
- Enki Multimedia (ASN: 209823).

Exchange                                      RV Collector           Router
--------------------------------------------  ---------------------  -----------------------
DE-CIX New York: DE-CIX New York Peering LAN  206.82.105.7           206.82.105.109
DE-CIX New York: DE-CIX New York Peering LAN  2001:504:36::192f:0:1  2001:504:36:0:3:339:0:1

**Comment by benoitc** [comment]
Hi Nina,

Thanks for the answer. Yes It's OK for me. I will setup the connection as well on my side 

Benoit

**Comment by nihb333** [comment]
Hi Benoit
I have configured our side as well.  I have nexthop_set failed messages in my log.  Do you see anything in your log?  I notice a 90+ ms RTT when I ping your IP address.

**Comment by benoitc** [comment]
@nihb333 this should be OK now : 

decix_nyc_routeviews_6447_ipv4 BGP        ---        up     23:28:21.379  Established
decix_nyc_routeviews_6447_ipv6 BGP        ---        up     23:28:22.282  Established

sorry for the delay, I got sidetracked.

**Comment by nihb333** [comment]
perfect - thank you!
