### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by m-paesani** [routeviews/public-issues#175]
### Full Name

AS5398

### ASN

5398

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

193.221.216.44 both IPv4/IPv6 on same session

### Multihop

- [X] Multihop Peering Request

**Comment by nihb333** [comment]
Hi

Thanks for your interest in the RputeViews Project.  We will be happy to peer.  
Are you able to send us your full routing table on these sessions?   
We do prefer a session per protocol and do not support receiving v6 routes on a v4 session, so please provide a v6 address for the v6 session if possible.

Our information for the multihop sessions is:
- asn:  6447
- ipv4: 128.223.51.113
- ipv6: 2001:468:d01:33::113
- fqdn: route-views7.routeviews.org

Kind regards

Nina

**Comment by m-paesani** [comment]
Hi Nina,
we are ready:

  Peer                                      AS  MsgRcvd  MsgSent  OutQ
 Up/Down       State    RtRcv    RtAdv
  128.223.51.113                          6447        0        4     0
00:03:11      Active        0        0
  2001:468:D01:33::113                    6447        0        1     0
00:00:28      Active        0        0

Our detail info:

   - asn: 5398
   - ipv4: 193.221.216.44
   - ipv6: 2A0F:E880::304

Please configure your side and let us know, thank you.

Kind regards,


-----

Marco Paesani




Skype: mpaesani
Mobile: +39 348 6019349
Success depends on the right choice !
Email: ***@***.***




Il giorno gio 7 nov 2024 alle ore 16:17 nihb333 ***@***.***>
ha scritto:

**Comment by nihb333** [comment]
Hi Marco

And finally are we - Thank you for the support!

route-views7.routeviews.org# sh bg su | include 5398
193.221.216.44  4       5398    144872         7 170401515    0    0 00:04:35       956928        0 AS5398 SA
2a0f:e880::304          4       5398     52811         7 98082550    0    0 00:04:35       211046        0 AS5398 SA
route-views7.routeviews.org#
