### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by chrismfz** [routeviews/public-issues#177]
### Full Name

Chris Panagiotakis

### ASN

AS216285

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

84.54.49.1
2a14:4280:1:1::1

### Multihop

- [ ] Multihop Peering Request

**Comment by nihb333** [comment]
Hi Christos - thanks for your interest in RouteViews.  We will be happy to set up a multihop peering with you where you announce your full routing table to us.  Please configure your session to:

IPv4: 128.223.51.113
IPv6: 2001:468:d01:33::113
ASN:  6447
FQDN: route-views7.routeviews.org

and let us know when done.  Then we will configure our side

BR Nina

**Comment by chrismfz** [comment]
Hello Nina, just did it!

**Comment by chrismfz** [comment]
Hello there! Any news on that ?

**Comment by nihb333** [comment]
Hi Chris

Sorry about the delay - our side is configured and the sessions are up - thanks for the support!
route-views7.routeviews.org# sh bg su | include 216285
84.54.49.1      4     216285    329313        17 170354958    0    0 00:02:28       956911        0 My IP Networks
2a14:4280:1:1::1        4     216285     85126        17 98069339    0    0 00:02:28       211592        0 My IP Networks
route-views7.routeviews.org#
