### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by wakuwakujp** [routeviews/public-issues#178]
### Full Name

Wakuwaku

### ASN

401111

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

140.235.196.1

### Multihop

- [X] Multihop Peering Request

**Comment by nihb333** [comment]
Hi

Thank you for interest in peering with RouteViews.  Since this is a multihop session, we do require that you will announce the full internet table to us as you would to a downstream transitcustomer.  Is this agreeable to you? 

Best regards 
Nina

**Comment by wakuwakujp** [comment]
Hello,

We agree to announce the full internet table.

Please let me know the next steps. Thank you.

**Comment by nihb333** [comment]
Great news!  Please configure the ebgp multihop session to and let us know when done.  Then we will confgure our side

Pv4: 128.223.51.113
IPv6: 2001:468:d01:33::113
ASN:  6447
FQDN: route-views7.routeviews.org

BR Nina

**Comment by wakuwakujp** [comment]
Our side has been configured.

Thank you.

**Comment by nihb333** [comment]
Thanks - session is up.  Let us know if you are interested in a v6 session as well

Thanks for the support!

route-views7.routeviews.org# sh bg su | include 401111
140.235.196.1   4     401111    257773        77 173470828    0    0 01:14:28       963186        0 Wakuwaku
route-views7.routeviews.org#
