### ISSUE TITLE
VOX AS11845 Peering Request

### ISSUE THREAD

**Issue by francoisv100** [routeviews/public-issues#183]
### Full Name

Voxtelecom

### ASN

11845

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

196.60.8.214 196.60.8.146 2001:43f8:6d0::214 2001:43f8:6d0::e

### Multihop

- [ ] Multihop Peering Request

**Comment by nihb333** [comment]
Hi Francois - thanks for this.  We are happy to peer and as discussed with Chris Burrel, we'd prefer if you will announce your full table to us as you would to a transit customer.  

Our information on NAPAfrica is:

AS: 6447

NAPAfrica IX Johannesburg: Peering  196.60.9.68 
NAPAfrica IX Johannesburg: Peering  2001:43f8:6d0::9:68

Our side is ready,s o please configure you side when convieniet.

route-views.napafrica.routeviews.org# sh bg su | include 11845
196.60.8.146    4      11845         0         0        0    0    0    never      Connect        0 Voxtelecom
196.60.8.214    4      11845         0         0        0    0    0    never      Connect        0 Voxtelecom
2001:43f8:6d0::e      4      11845        24         9        0    0    0    never         Idle        0 Voxtelecom
2001:43f8:6d0::214    4      11845        24        10        0    0    0    never         Idle        0 Voxtelecom

Thanks for the support 

Nina

**Comment by francoisv100** [comment]
Thanks , BGP sessions setup on our side and they are now established , let us know if there is anything else required,

196.60.9.68            6447         13        117       0       0        5:05 Establ
2001:43f8:6d0::9:68        6447         12         20       0       0        4:38 Establ

196.60.9.68            6447          9        115       0       0        3:08 Establ
2001:43f8:6d0::9:68        6447          9         17       0       0        3:09 Establ

**Comment by nihb333** [comment]
Hi Francois

Thanks - I see the sessions up.  I was expecting however that you would announce the full table to us as you would to a transit downstream customers, but it looks like this is a session with the BGP policy for a reular peering session.  would it be possible for you to announce the full internet table?

**Comment by francoisv100** [comment]
bgp policy amended you will see the full tables coming in for v4 and v6,  advertising prefixes are ramping up my side : ) 

show bgp neighbor 196.60.9.68 | match "Advertised prefixes" 
    Advertised prefixes:          463985

show bgp neighbor 196.60.9.68 | match "Advertised prefixes"    
    Advertised prefixes:          485643

show bgp neighbor 196.60.9.68 | match "Advertised prefixes"    
    Advertised prefixes:          494621

 show bgp neighbor 196.60.9.68 | match "Advertised prefixes"    
    Advertised prefixes:          500550

 show bgp neighbor 196.60.9.68 | match "Advertised prefixes"    
    Advertised prefixes:          515396

 show bgp neighbor 2001:43f8:6d0::9:68 | match "Advertised prefixes" 
    Advertised prefixes:          201791

show bgp neighbor 2001:43f8:6d0::9:68 | match "Advertised prefixes"    
    Advertised prefixes:          201796

**Comment by nihb333** [comment]
Great - thank you!!  I see the full tables - lovely - thanks for the help and the support
