### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by legacyobj** [routeviews/public-issues#186]
### Full Name

Minjae Kim

### ASN

AS215343

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

2.59.252.1

### Multihop

- [X] Multihop Peering Request

**Comment by nihb333** [comment]
Hi Minjae

Thanks for your interest in peering with RouteViews.  It is not clear what type of network your are operating and we see very little information in PeeringDB, RIPEDB.  The link to your website and LinkedIn profiles are both dead.   So we will have to decline this request
