### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by wltsousa** [routeviews/public-issues#189]
### Full Name

Wellington Sousa da Silva

### ASN

61618

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [X] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [ ] Multihop Peering Request

**Comment by nihb333** [comment]
Hi Wellington.  I assume this ticket was about the ASN change?  If not please let me know 
BR Nina

**Comment by wltsousa** [comment]
Yes
Atenciosamente
Wellington Sousa
Tel/Cel: +55 71 99627-4353

> Em 19 de dez. de 2024, à(s) 12:37, nihb333 ***@***.***> escreveu:
> 
> Hi Wellington. I assume this ticket was about the ASN change? If not please let me know
> BR Nina
