### ISSUE TITLE
decix.jhb is not accessible

### ISSUE THREAD

**Issue by chong601** [routeviews/public-issues#191]
### Effected Services/Hosts

decix.jhb.routeviews.org

### Details

Just want to inform that the collector for decix.jhb terminates the connection as soon as the Telnet session is established.

A sample of the console output has been added below.

### Console output or logs

```shell
$ telnet decix.jhb.routeviews.org
Trying 113.23.189.74...
Connected to decix.jhb.routeviews.org.
Escape character is '^]'.
Connection closed by foreign host.
```

**Comment by pfsinoz** [comment]
Thanks for letting us know, we are investigating with the JHB site now. It appears as though the collector has run out of resources for some reason.

**Comment by pfsinoz** [comment]
The collector is back in service now. Thanks for letting us know about the access issue.
```
% telnet decix.jhb.routeviews.org
Trying 113.23.189.74...
Won't send login name and/or authentication information.
Connected to decix.jhb.routeviews.org.
Escape character is '^]'.

Hello, this is FRRouting (version 10.2).
Copyright 1996-2005 Kunihiro Ishiguro, et al.

decix>
```
